# basic options, hello
title: MyBlog
author: luvifer
email: aashishsolanki1@gmail.com
description: a nubbie
twitter: luvifer03
instagram: luvifer_
linkedln: Aashish Solanky
github_username: luvifer03

# Build settings
mardown: kramdown
theme: minima
